services:
  api:
    build: 
      context: .
      args:
        ENV: dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: >
      sh -c "mkdir -p /app/logs && touch /app/logs/app.log && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"